clusterHealthCheckParams: wait_for_status=yellow&timeout=1s
esJavaOpts: -Xmx768m -Xms768m
esPlugins:
- repository-s3
minimumMasterNodes: 1
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1.5Gi
  requests:
    cpu: 500m
    memory: 1Gi
xpack:
  ml:
    enabled: false

# Add this section for S3 credentials
keystore:
  - secretName: elasticsearch-s3-credentials
