service:
  type: NodePort

resources:
  requests:
    cpu: "200m"
    memory: "768Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearchSsl:
  verificationMode: "none"

secretMounts: []

extraEnvs:
  - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
    valueFrom:
      secretKeyRef:
        name: kibana-elasticsearch-token
        key: token
  - name: NODE_OPTIONS
    value: "--max-old-space-size=512"
